apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mypod2s1
  name: mypod2s1
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
   run: ashupod2
  type: NodePort
status:
  loadBalancer: {}
